services:
  # ubuntu-fuzz:
  #   container_name: ubuntu-fuzz
  #   build:
  #     dockerfile: Dockerfile.fuzz
  #   restart: unless-stopped
  #   tty: true

  afl:
    container_name: afl
    build:
      dockerfile: Dockerfile.afl
    restart: unless-stopped
    privileged: true 
    tty: true
    volumes:
      - .:/workspace