# Build environment
FROM ubuntu:noble

# Install Ubuntu packages
RUN apt-get update -y \
    && DEBIAN_FRONTEND="noninteractive" apt-get install -y \
        git \
        make \
        cmake \
        clang \
        gdb \
        valgrind \
        libtool \
        automake \
        autoconf \
        afl++ \
        llvm \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /workspace

# Copy source code
COPY . .

# git submodule update --init && autoreconf -i && \
# export AFL_USE_ASAN=1 && \
# CC=afl-clang-lto CXX=afl-clang-lto++ AR=llvm-ar RANLIB=llvm-ranlib \
# ./configure --with-oniguruma=builtin && \
# make clean && make -j8
